#Mad Libs Game

first_noun = input ("Enter a noun: ")
num_noun = input ("Enter a large number: ")
Second_noun = input ("Enter a noun: ")
First_adjective = input ("Enter an adjective: ")
Second_adjective = input ("Enter a Color: ")
Third_adjective = input ("Enter an adjective: ")
First_verb = input ("Enter a verb ending in -ing: ")
Forth_adjective = input ("Enter an adjective: ")
Second_verb = input ("Enter a verb: ")
Third_verb = input ("Enter a verb ending in -ing: ")
Third_noun = input ("Enter a noun: ")
Forth_noun = input ("Enter a noun: ")
Fifth_adjective = input ("Enter an adjective: ")
Fifth_noun = input ("Enter the name of a place: ")
Forth_verb = input ("Enter a verb: ")
Sixth_noun = input ("Enter a noun: ")
Seventh_noun = input ("Enter a noun: ")
Fifth_verb = input ("Enter a verb ending in -ing: ")
Sixth_verb = input ("Enter a verb: ")
Sixth_adjective = input ("Enter an adjective: ")

print("Yoda is a jedi " + first_noun + " who trained Jedi for " + num_noun + " years about how to use The " + Second_noun +". He is known for his " + First_adjective + " size, " + Second_adjective + " skin and " + Third_adjective + " way of " + First_verb + " words.")
print("In the movie Star Wars: A " + Forth_adjective + " Hope, Luke Skywalker " + Second_verb + "s Yoda after " + Third_verb + " his " + Third_noun + " into a " + Forth_noun + " on a " + Fifth_adjective + " planet called " + Fifth_noun + ". Yoda " + Forth_verb + "s Luke to become a Jedi " + Sixth_noun +".")
print("Yoda remains a " + Seventh_noun + " to Luke, " + Fifth_verb + " him to use The Force to " + Sixth_verb +" " + Sixth_adjective + " Vader and the Empire.")